# -*- coding: utf-8 -*-
"""Salary_pred

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LKctape0ojL6181lvr4wb83-yskcKRXf
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/Sakshi100304/salary_pred/refs/heads/main/Salary_Dataset_DataScienceLovers.csv")
df
for column in df.columns:
    df[column] = pd.to_numeric(df[column], errors='coerce')

df.isnull().sum()

for column in df.columns:
  if df[column].dtype == object:
    #fill categorical colums with the mode
    df[column] = df[column].fillna(df[column].mode()[0])
  else:
    #fill numerical colums with the mean
    df[column] = df[column].fillna(df[column].mean())
    print(df.isnull().sum())

df = pd.get_dummies(df, drop_first=True)

print(df.head())

# Separate features (X) and target (y)
X = df.drop('Salary', axis=1)
y = df['Salary']

print('Features (X) head:')
print(X.head())

print('\nTarget (y) head:')
print(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'y_train shape: {y_train.shape}')
print(f'y_test shape: {y_test.shape}')

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor


# Initialize all models in a dictionary
models_to_train = {
    'Linear Regression': LinearRegression(),
    'K-Nearest Neighbors': KNeighborsRegressor(n_neighbors=5),
    'Support Vector Machine': SVR(),
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(n_estimators=100, random_state=42),
   
}

y_preds_dict = {}

print('Training models and making predictions in a loop...')
for model_name, model in models_to_train.items():
    print(f'\n--- Training {model_name} ---')
    model.fit(X_train, y_train)
    y_preds_dict[model_name] = model.predict(X_test)
    print(f'{model_name} Trained and Predictions Made.')

print('\nAll models trained and predictions collected.')

"""### Model Evaluation"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

results = {}

print('Calculating evaluation metrics for each model...')
for model_name, y_pred in y_preds_dict.items():
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    results[model_name] = {'MAE': mae, 'MSE': mse, 'R2 Score': r2}

# Display results
print('\nModel Evaluation Results:')
for model_name, metrics in results.items():
    print(f'\n--- {model_name} ---')
    for metric_name, value in metrics.items():
        print(f'{metric_name}: {value:.2f}')

"""### Visual Comparison of Model Performance"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Convert results dictionary to a DataFrame for easier plotting
results_df = pd.DataFrame.from_dict(results, orient='index')

plt.figure(figsize=(18, 6))

# Subplot 1: MAE
plt.subplot(1, 3, 1) # 1 row, 3 columns, 1st subplot
sns.barplot(x=results_df.index, y='MAE', data=results_df, palette='viridis')
plt.title('Model Mean Absolute Error (MAE)')
plt.xlabel('Model')
plt.ylabel('MAE')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Subplot 2: MSE
plt.subplot(1, 3, 2) # 1 row, 3 columns, 2nd subplot
sns.barplot(x=results_df.index, y='MSE', data=results_df, palette='magma')
plt.title('Model Mean Squared Error (MSE)')
plt.xlabel('Model')
plt.ylabel('MSE')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Subplot 3: R2 Score
plt.subplot(1, 3, 3) # 1 row, 3 columns, 3rd subplot
sns.barplot(x=results_df.index, y='R2 Score', data=results_df, palette='cubehelix')
plt.title('Model R2 Score')
plt.xlabel('Model')
plt.ylabel('R2 Score')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout() # Adjust layout to prevent labels from overlapping
plt.suptitle('Comparison of Model Performance Metrics', y=1.02, fontsize=16) # Overall title
plt.show()

import pickle

# Identify the best model (Linear Regression based on R2 Score and MSE)
best_model_name = 'Linear Regression'
best_model = models_to_train[best_model_name]

# Define the filename for the pickled model
model_filename = f'{best_model_name.lower().replace(" ", "_")}_model.pkl'

# Save the best model to a .pkl file
with open(model_filename, 'wb') as file:
    pickle.dump(best_model, file)

print(f"Best model ('{best_model_name}') saved as '{model_filename}'")
print("You can download this file from the Colab file browser (left-hand panel -> folder icon).")
